name:  Hacktoberfest Label
on:
  issues:
    types: [opened,labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: hacktoberfest-action
        uses: mdb571/hacktoberfest-action@master
        env:
          LABEL_COLOR: ${{#9400D3}}
          LABEL_FILTER: ${{secrets.LABEL_FILTER}}
